version: '3.9'
services:
  fastapi:
    build: .
    container_name: fastapi-container
    environment:
      - DEBUG=$DEBUG
      - PROFILING_ENABLED=$PROFILING_ENABLED
      - MASTER_DB_USER=$MASTER_DB_USER
      - MASTER_DB_PASSWORD=$MASTER_DB_PASSWORD
      - MASTER_DB_HOSTNAME=$MASTER_DB_HOSTNAME
      - MASTER_DB_PORT=$MASTER_DB_PORT
      - MASTER_DB_NAME=$MASTER_DB_NAME
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
      - ALGORITHM=$ALGORITHM
      - PORT=$PORT
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-fastapi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  app-network:
    driver: bridge
