"""update reletion for group

Revision ID: a134aab51e30
Revises: 1a1116cc1369
Create Date: 2024-11-25 18:31:56.784007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a134aab51e30'
down_revision: Union[str, None] = '1a1116cc1369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_group_id', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('fk_messages_group_id', 'messages', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
