"""update is_private to bool

Revision ID: be8164cdd5c7
Revises: 0774518df2ea
Create Date: 2024-11-25 10:48:18.188949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8164cdd5c7'
down_revision: Union[str, None] = '0774518df2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'is_private',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using="is_private::boolean",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'is_private',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               postgresql_using="is_private::integer",
               existing_nullable=True)
    # ### end Alembic commands ###
